# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lincolnwood Lightning Swim Team
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lwlightning.org" # the base hostname & protocol for your site
menus:
    main:
    - Handbook & Fees:
        - Swim Team Fees: /swimteam-handbook/summer-season-swim-team-fees.html
        - Home & Away Meets: /swimteam-handbook/home-away-meets.html
        - Information: /swimteam-handbook/information.html
        - LLSC Apparel: /swimteam-handbook/llsc-apparel.html
        - Questions & Communication: /swimteam-handbook/communication.html
        - Championship Meet: /swimteam-handbook/championship-meet.html
        - NISC Order of Events: /swimteam-handbook/nisc-order-of-events.html
        - Non-Resident Pass: /swimteam-handbook/non-resident-pass.html
    - 2020 Season Info: /2020-calendar.html
    - Practice Schedule: /practice-schedule/
    - Stroke Clinic: /stroke-clinic/
    - Gear: /lincolnwood-gear.html
    - Meet Schedule: /meet-schedule.html
    - Meet Signup: /meet-signup/
    - Maps: /maps/
    - Photos: /photos/



# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json]
